# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ci_width": "00_core.ipynb",
         "expand_bbox": "00_core.ipynb",
         "annotate_label": "00_core.ipynb",
         "funnel_plot": "00_core.ipynb",
         "bootstrap": "00_core.ipynb",
         "funnel_plot_bootstrap": "00_core.ipynb",
         "funnel": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://johnhw.github.io/funnelplot/"

git_url = "https://github.com/johnhw/funnelplot/tree/master/"

def custom_doc_links(name): return None